name: kluner
favicon: null
layout_spectrum: 0.50876
typography_spectrum: 0.50292
title: 'sysadmin madness, in relative perspective'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.22215779195539653
  lightness: 0.5221426791977137
  saturation: 0.5
  rhythmicContrast: 0.313166412524879
purpose: []
